name: Build and Test [Python 3.9]

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build using Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: install dependencies [pip]
        run: |
          python -m pip install pip --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .

      - name: run linter [flake8]
        run: flake8 .

      - name: run unit tests
        run: test

